version: '2'

services:
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:5.4.0'
        ports:
            - '9200:9200'
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data
            - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    frontend:
        build: ./frontend/
        ports:
            - '420:80'
        volumes:
            - './frontend:/dora'
    worker:
        build: ./worker/
        restart: always
        depends_on:
            - 'elasticsearch'
        links:
            - 'elasticsearch:elasticsearch'
